# Generated by Django 3.2.4 on 2022-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_conducted',
            field=models.BooleanField(default=False),
        ),
    ]
