# Generated by Django 3.2.4 on 2022-11-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_conducted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='event',
            name='registrations_open',
            field=models.BooleanField(default=True),
        ),
    ]
