# Generated by Django 3.2.4 on 2022-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20221111_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.CharField(max_length=250),
        ),
    ]
