# Generated by Django 3.2.4 on 2022-11-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220206_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='googleplus_link',
            new_name='mail_link',
        ),
        migrations.AddField(
            model_name='team',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
    ]
