# Generated by Django 3.2.4 on 2021-10-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
