# Generated by Django 3.2.4 on 2022-11-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20220206_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name_plural': 'Research'},
        ),
    ]
